---
editor_options: 
  markdown: 
    wrap: 72
---

# Team Microplastic's FIRE Summit Presentation

Sammi, Neha, Lasya, Sriya, Chayanika

## Research Question

What are the effects of the plastic bag ban on microplastic pollution in
the Chesapeake Bay?

How does emissions from battery recycling plants impact water pollution
in the Chesapeake Bay?

(Optional) Insert an image if it helps motivate the research question.

## Data Wrangling

**Outcome variable**

Write description, data source, and wrangling methodology. Show a map if
you have made one.

If you have loops, do not run the entire thing. Instead, run one sample
loop or just display your codes without making it run by adding **#\|
eval: false** at the top of the chunk.

# You can also suppress warnings by adding **#\| warning: false**.

Our outcome variable is water quality from each county adjacent to the
Chesapeake Bay. Specific water parameters that we are interested in
include total nitrogen, total carbon, and total organic nitrogen.

This data is obtained from
[https://datahub.chesapeakebay.net](https://datahub.chesapeakebay.net/)
which reports water quality from each county each day.

```{r}
#| warning: false
install.packages("tidyverse")
install.packages("terra")
install.packages("simplermarkdown")

library("tidyverse")
library("terra")
library("simplermarkdown")

df<- read.csv("WaterQualityFIPS.csv") %>%
  rename(fips=FIPS)

fips<-read.csv("state_and_county_fips_master.csv")

dfcounty<-merge(df, fips, by="fips", all.x=TRUE) %>%
  mutate(SampleDate=as.Date(SampleDate, format='%m/%d/%Y')) %>%
  mutate(Month=month(SampleDate), Year=year(SampleDate)) %>%
  group_by(Parameter, Unit, fips, name, state, Month, Year) %>%
  summarize(MeasureValue=mean(MeasureValue))
```

**Treatment variable**

Write description, data source, and wrangling methodology. Show a map if
you have one.

**Control variables**

Write description, data source, and wrangling methodology. Show a map if
you have one.

## Preliminary Results

# Display a figure showing how the treatment variable impacted the outcome variable.

Our treatment variable is an indicator of whether there is a plastic bag
ban or tax in each county. This data set came
from <https://www.bagtheban.com/in-your-state/>.

**Control variables**

To take into account total precipitation and average storm-water runoff
data we used data from NASA Earth Data. Our data came from GLDAS Noah
Land Surface Model.

## Preliminary Results
